# Generated by Django 4.2.3 on 2023-08-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirm_key',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='код подтверждения почты'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_is_confirmed',
            field=models.BooleanField(default=False, verbose_name='подтверждено'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='аватар'),
        ),
    ]
