# Generated by Django 4.2.3 on 2023-08-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version',
            field=models.CharField(max_length=20, verbose_name='номер версии'),
        ),
    ]
