# Generated by Django 4.2.3 on 2023-09-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_options_alter_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('created', 'добавлен'), ('moderated', 'на модерации'), ('published', 'опубликован')], default='moderated', max_length=20, verbose_name='статус'),
        ),
    ]
